# Generated by Django 2.2.12 on 2021-03-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='destroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supply', models.CharField(choices=[('S', 'Sledge hammer'), ('B', 'Bat'), ('C', 'Chainsaw')], default='S', max_length=1)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Furniture')),
            ],
        ),
    ]
